# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(890, 920)
        Dialog.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        Dialog.setAcceptDrops(False)
        icon = QtGui.QIcon.fromTheme("x-office-document")
        Dialog.setWindowIcon(icon)
        Dialog.setAutoFillBackground(False)
        Dialog.setSizeGripEnabled(False)
        Dialog.setModal(False)
        Dialog.setWindowIcon(QtGui.QIcon('pdf.png'))
        self.btnBrowse = QtWidgets.QPushButton(parent=Dialog)
        self.btnBrowse.setGeometry(QtCore.QRect(20, 10, 131, 31))
        self.btnBrowse.setObjectName("btnBrowse")
        self.graphicsView = QtWidgets.QGraphicsView(parent=Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(20, 50, 850, 850))
        self.graphicsView.setObjectName("graphicsView")
        self.nextButton = QtWidgets.QPushButton(parent=Dialog)
        self.nextButton.setGeometry(QtCore.QRect(796, 10, 75, 31))
        self.nextButton.setObjectName("next")
        self.previousButton = QtWidgets.QPushButton(parent=Dialog)
        self.previousButton.setGeometry(QtCore.QRect(680, 10, 75, 31))
        self.previousButton.setObjectName("previous")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "PDF Reader by Leonov M.N."))
        self.btnBrowse.setText(_translate("Dialog", "Загрузить"))
        self.nextButton.setText(_translate("Dialog", ">"))
        self.previousButton.setText(_translate("Dialog", "<"))
